"""cloudinary_media

Revision ID: 04265e8677a6
Revises: 649f79e45858
Create Date: 2025-12-17 20:38:57.773245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04265e8677a6'
down_revision: Union[str, None] = '649f79e45858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('public_id', sa.String(), nullable=False))
    op.alter_column('product_media', 'src',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('idx_product_media_cloudinary_id', table_name='product_media')
    op.create_index(op.f('ix_product_media_cloudinary_id'), 'product_media', ['cloudinary_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_media_cloudinary_id'), table_name='product_media')
    op.create_index('idx_product_media_cloudinary_id', 'product_media', ['cloudinary_id'], unique=False)
    op.alter_column('product_media', 'src',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('product_media', 'public_id')
    # ### end Alembic commands ###
