"""cloudinary_media_crud

Revision ID: 462a290f18bd
Revises: 04265e8677a6
Create Date: 2025-12-17 23:26:29.559879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462a290f18bd'
down_revision: Union[str, None] = '04265e8677a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_media', 'cloudinary_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_media', 'cloudinary_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
