"""cloudinary_media_crud_2.0

Revision ID: 9642c844de34
Revises: 462a290f18bd
Create Date: 2025-12-17 23:34:59.865868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9642c844de34'
down_revision: Union[str, None] = '462a290f18bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_media', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_media', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
